services:
  db:
    image: postgres:16-alpine
    container_name: stock_app_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stockdb
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
